### ISSUE TITLE
Проверка атрибутов на наличие  tr[class] ->> \\tag[@attr]

### ISSUE THREAD

**Issue by Niremizov** [olamedia/nokogiri#16]
В некоторых случаях бывает полезно выбирать элементы только в том случае, если у них присутствует какой-либо атрибут. Пример таблицы:

    <table>
        <tr></tr>
        <tr class='item'></tr>
        <tr class='item'></tr>
        ....
    </table>

В такой разметке, первая строка таблицы это заголовок, а далее идут уже элементы списка... Пример: http://www.dns-shop.ru/search/?length_1=0&q=delonghi

В данный момент в случае использовании $nokogiti->get('table.catalog_view_list tbody tr[data-price_item_id]') - атрибут вообще не попадает в XPath запрос.

**Comment by olamedia** [comment]
спасибо
