### ISSUE TITLE
fromDom() и toText и версия libxml

### ISSUE THREAD

**Issue by Niremizov** [olamedia/nokogiri#22]
Полагаю в README есть смысл добавить в Requirements информацию о минимальной версии libxml. Обнаружил при использовании Libxml версии 2.7.8 - появляется следующее поведение:

Функция:
` 
  public function getDomElementsText($dom_element) {

```
$parser = nokogiri::fromDom($dom_element);

return $parser->toText();
```

  }
`

На выходе вернет HTML/текст в неверной кодировке, думал проблема в версии PHP, но обновление до 5.5 не помогло. Сменил **libxml на 2.9.2** и HTML на выходе нормальный в UTF8.

**Comment by olamedia** [comment]
есть возможность проверить другие версии? чтобы указать минимальную для работы...

**Comment by Niremizov** [comment]
Нет к сожалению сейчас возможности потестировать данный момент нет.
