### ISSUE TITLE
Содержимое тега <script>

### ISSUE THREAD

**Issue by Sfairet** [olamedia/nokogiri#26]
Здравствуйте!

Не получается вытащить содержимое тега `<script>`. На сколько я понял, внутренности тега должны попасть в `#cdata-section`, но внутри всегда пустой массив.
Пример html:

`<script>writestat('show');</script>`

Читаем:

`$nakogiri->get('script')->toArray()`

Получаем:

```
Array
(
    [0] => Array
        (
            [#cdata-section] => Array
                (
                    [0] => Array
                        (
                        )

                )

        )

)
```

Получения атрибутов тега работает корректно.

**Comment by olamedia** [comment]
скорее в `#text`, тут же нет блока CDATA

**Comment by Sfairet** [comment]
@olamedia я содержимое изначально там и искал. Но такого ключа в итоговом массиве нет вообще.

**Comment by Sfairet** [comment]
Так и не смог понять, почему `#text` остается пустым. Есть какие-нибудь идеи или все-таки баг?

**Comment by olamedia** [comment]
можно воспользоваться getDom или toXml

**Comment by Sfairet** [comment]
Проверил, через getDom возвращается содержимое тега. 

Я не проверял глубоко в чем именно причина такого поведения, но в итоге вот что происходит:
функция `public function toArray($xnode = null)` читает рекурсивно `DOMNodeList` полученный от функции `protected function getElements($xpathQuery)` так:
`$nodeList = $this->getXpath()->query($xpathQuery);`

Теоретически содержимое тега `script` должно было попасть в список дочерних нод с именем `#text` и типом `XML_TEXT_NODE`. Так происходит для всех остальных тегов. Но в списке дочерних нод тега `script` есть только нода `#cdata-section` с пустым значением.

**Вот такой фикс поможет получать значение тега `script` через метод `toArray`:**
В функции `public function toArray($xnode = null)` 
После блока кода:
`
if (in_array($node->nodeType, array(XML_TEXT_NODE,XML_COMMENT_NODE))){
return $node->nodeValue;
}
`

Добавить:
`
if( $node->nodeName == 'script' ){
$array['#text'][] = $node->nodeValue;
}
`

**Comment by olamedia** [comment]
скорее, тип ?XML_CDATA_NODE? добавить в этот массив, есть возможность проверить?

**Comment by olamedia** [comment]
я только не понял, почему не text, а cdata, это html или xml?

**Comment by Sfairet** [comment]
Это HTML.
XML_CDATA_SECTION_NODE  - не получится. Само значение тега скрипт есть только когда мы находимся на нем как на ноде. У него есть дочерняя нода `#cdata-section`, у неё как раз тип `XML_CDATA_SECTION_NODE`, но она пустая. Содержимое тега в неё не попадает.

**Comment by Sfairet** [comment]
У тега скрипт соответсвенно тип `XML_ELEMENT_NODE`

**Comment by Sfairet** [comment]
Да, я ошибся. Сейчас проверил через отладчик, все верно, у самой #cdata-section значение все-таки есть. И модно заменить
`in_array($node->nodeType, array(XML_TEXT_NODE,XML_COMMENT_NODE)`

На
`in_array($node->nodeType, array(XML_TEXT_NODE,XML_COMMENT_NODE, XML_CDATA_SECTION_NODE)`

Тогда содержимое скрипта попадет в массив с ключом `#cdata-section`.

Правда мне то как раз содержимое нужно было в #text

**Comment by Sfairet** [comment]
И еще маленький тест. В исходном варианте, на таком примере:

```
<script>alert(1);
		<tag>i am in script</tag>
</script>
<script>
	<![CDATA[<sender>John Smith</sender>]]>
</script>
```
`#cdata-section` все равно останется пустым. С фиксами, описанными выше, почему-то остается закрывающий элемент `]]>`

То есть мы получим такой результат при Xpath = "script"
```
array(2) {
  [0]=>
  array(2) {
    ["#text"]=>
    array(1) {
      [0]=>
      string(35) "alert(1);
		i am in script
	"
    }
    ["#cdata-section"]=>
    array(1) {
      [0]=>
      string(35) "alert(1);
		i am in script
	"
    }
  }
  [1]=>
  array(2) {
    ["#text"]=>
    array(1) {
      [0]=>
      string(36) "
	John Smith]]>
	"
    }
    ["#cdata-section"]=>
    array(1) {
      [0]=>
      string(36) "
	John Smith]]>
	"
    }
  }
}
```

**Comment by olamedia** [comment]
а импорт идет через какой метод? loadHtmlNoCharset?
может ему доктайпа не хватает?

**Comment by Sfairet** [comment]
Импорт через конструктор 
`$this->loadHtml($htmlString);`
Но у меня там обработки стоят которые заменяют исходные данные в HTML о кодировке на понятный ему html4 формат (т.к. даже с верным доктайпом ни формат html5 задания кодировки, ни xml формат DOMDocument::loadHTML не понимает и пытается исходный utf-8 перекодировать как будто это iso-8859-1).
Возможно просто у меня PHP устарел уже, на сервере стоит `5.3.3`

**Comment by Sfairet** [comment]
Сам входящий HTML очень разный, на сегодняшний день я разбираю больше 300 сайтов на постоянной основе.

**Comment by olamedia** [comment]
возможно, устарел. может даже не php, а библиотеки в системе.
loadHtmlNoCharset делает то же самое. он принудительно выставляет доктайп и кодировку utf-8

**Comment by Sfairet** [comment]
Проблема в том, что кодировка не всегда utf8, в ру сегменте не редкость сайты с windows-1251. Поэтому мне нужно было вытаскивать верную кодировку и подставлять её в понятном html4 формате мета тегом.
По сути тоже самое, что и loadHtmlNoCharset, но с сохранением исходной кодировки, заданной в разных форматах.
Вообще в планах скоро переезд на новый сервер, там поставлю php посвежее с последними библиотеками, потестируем как пойдет.
