### ISSUE TITLE
Получить следующий невложенный элемент.

### ISSUE THREAD

**Issue by nepohex** [olamedia/nokogiri#27]
Доброго дня! Спасибо большое за инструмент, очень удобно! Столкнулся с проблемой и никак не могу решить, подскажите пожалуйста. 

У меня есть DIV , в нем лежат вперемешку не вложенные никуда элементы IMG / p / h3, от 10 до 50 каждого может быть . 

Как получить следующий за IMG элемент H3 или наоборот? 

```
$items_all = $saw->get('div.post_content')->toArray();
items_all = {array} [1]
 0 = {array} [6]
  class = "post_content"
  itemprop = "articleBody"
  #text = {array} [28]
  p = {array} [12]
  div = {array} [6]
  h3 = {array} [10]

```

**Comment by nepohex** [comment]
Пример структуры документа (HTML выводится сразу кодом, никак не могу его вывести норм, надо исходный смотреть чтобы получить):

> <root>
> <div class="post_cont">
> <h3>#2: African American Queen</h3>
> <p style="text-align: left;">
> Short hairstyles for black women are killing the hair game lately â this look is leading the pack. The side part of this gorgeous bob sits lower than your average side part for a statement sweep that speaks chic and perfection.
> </p>
> <div style="width: 510px" class="wp-caption aligncenter">
> <img src="http://i1.wp.com/therighthairstyles.com/wp-content/uploads/2013/11/2-black-sideparted-bob.jpg?w=500" alt="Black Side-Parted Bob" data-recalc-dims="1"/>
> <p class="wp-caption-text">
> <a href="https://www.instagram.com/p/BAQD8fiBjv6/" target="_blank" rel="nofollow">Source</a>
> </p>
> </div>
> <h3>#3: Short, Black, and Choppy</h3>

Получить элементы кодом ниже не получается:
```
$tmp[] = $saw->get('div.post_cont:nth-child(even)')->toArray();
$tmp[] = $saw->get('div.post_cont:nth-child(5)')->toArray();
$tmp[] = $saw->get('div.post_cont:last-child')->toArray();
$tmp[] = $saw->get('div.post_cont:first-child')->toArray();
```

А вот такой код извлекает все h3:
`$tmp[] = $saw->get('div.post_cont h3:nth-child(even)')->toArray();`

**Comment by olamedia** [comment]
такие вопросы стоит задавать на stackoverflow или askdev

**Comment by nepohex** [comment]
Да я бы задал, но там про ваш класс никто не знает. Да и не работают first-child и другие псевдо классы, сколько не пробовал.

**Comment by olamedia** [comment]
Просто этот вопрос не относится к классу.

>Да и не работают first-child и другие псевдо классы, сколько не пробовал.
возможно, вы не понимаете, как они должны работать?

Могу предложить разобрать на массив из img и h3, а по нему уже пройтись ручками, раз никакой структуры в документе нет.
