### ISSUE TITLE
Не работают псевдоклассы

### ISSUE THREAD

**Issue by Dragon-Knight** [olamedia/nokogiri#30]
Видимо проекту конец, однако это пока это самый лучший парсер, среди попробованных...

На странице есть 10 штук `<table class="weather-table"> ... </table>`. Нужно выбрать первую таблицу.
Пишу `$saw_page->get(".weather-table:first-child")->toArray();` и получаю все 10 таблиц.
Помогите пожалуйста исправить.

**Comment by olamedia** [comment]
Первую внутри одного контейнера? Типа как ниже?
```html
<div>
   <table class="weather-table"> ... </table>
   <table class="weather-table"> ... </table>
</div>
```

**Comment by Dragon-Knight** [comment]
Не знал что работает только на одном уровне. Я думал что первый во всей выборке.
На самом деле структура такая: 10 штук `<div class="card"></div>`, а внутри по одному `<table class="weather-table"> ... </table>`.

Спасибо за ответ и за парсер!

**Comment by olamedia** [comment]
Предлагаю попробовать новую версию кстати

**Comment by Dragon-Knight** [comment]
Ого, проект жив и версия 2 стала куда интереснее, однако к сожалению использовать я её не смогу, - код должен работать на 5.4, 5.5 :(

**Comment by olamedia** [comment]
бывает, поэтому и сделал отдельную ветку и тег.
в принципе, новые фичи особо не используются. попробую вернуть совместимость, может малыми правками обойдется.
