### ISSUE TITLE
Корректная загрузка UTF-8 при отсутствии признаков в документе

### ISSUE THREAD

**Issue by olamedia** [olamedia/nokogiri#4]
Сделать ли отдельный метод?

Варианты

Вставка XML тега, удаление после загрузки

```
$doc = new DOMDocument();
$doc->loadHTML('<?xml encoding="UTF-8">' . $html);
// dirty fix
foreach ($doc->childNodes as $item)
    if ($item->nodeType == XML_PI_NODE)
        $doc->removeChild($item); // remove hack
$doc->encoding = 'UTF-8'; // insert proper
```

Вставка meta после head

```
$html=preg_replace('/<head[^>]*>/','<head><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">',$html); 
```

**Comment by indiarocks08** [comment]
I am getting this symbol : â—† in place of ◆ symbol , I am using UTF8 , for Playstore URL's .. Pls help

**Comment by olamedia** [comment]
@indiarocks08 i wish to help, but
1. you provided no url, and very little information about how you fetching html and feeding it to the library
2. your question is better ask at stackoverflow, since it's most likely not an library fault, but url fetching error or something like it.
3. create new issue next time, please
